name: Master CI/CD

on:
  push:
    branches:
      - main

jobs:
  primary:

    runs-on: ubuntu-latest

    steps:
    - uses: ravsamhq/notify-slack-action@v1
      if: always()
      with:
        status: ${{ job.status }} # required
        notification_title: '{workflow} has {status_message}'
        message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
        footer: 'Linked Repo <{repo_url}|{repo}>'
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: yarn install
    - name: lint
      run: yarn lint
    - name: generate
      run: yarn generate
    - name: serverless deploy
      run: npx serverless deploy
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notify_when: 'failure'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
